spring:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                search:
                    default:
                        directory_provider: filesystem
                        indexBase: /tmp/lucene/indexes
    datasource:
        url: jdbc:mariadb://localhost:3306/testdb
        username: root
        password:
